#ifndef AST_BINARY_OPERATION_H
#define AST_BINARY_OPERATION_H

#include <ast/ast.h>

enum AST_BINARY_OPERATION : uint8_t
{
	AST_BINARY_ADDITION,
	AST_BINARY_SUBTRACTION,
	AST_BINARY_MULTIPLICATION,
	AST_BINARY_DIVISION,
	AST_BINARY_EXPONENTATION,
	AST_BINARY_MODULO,
	AST_BINARY_CONCATENATION,
	AST_BINARY_LESS_THAN,
	AST_BINARY_LESS_EQUAL,
	AST_BINARY_GREATER_THEN,
	AST_BINARY_GREATER_EQUAL,
	AST_BINARY_EQUAL,
	AST_BINARY_NOT_EQUAL,
	AST_BINARY_AND,
	AST_BINARY_OR
};

struct BinaryOperation
{
	AST_BINARY_OPERATION type;
	Ast::Expression* leftOperand = nullptr;
	Ast::Expression* rightOperand = nullptr;
};

#endif // AST_BINARY_OPERATION_H
